#####################################################################
# Makefile
# device main makefile
# Willster419
# 2020-07-31
# Compiles all listed devices and includes modelsim flow makefile
#####################################################################

# define root paths
REPO_ROOT    = $(abspath ../../)
PROJECT_PATH = $(abspath ../)
SCRIPTS_DIR  = $(REPO_ROOT)/scripts
LIB_DIR      = $(PROJECT_PATH)/build
RUN_DIR      = $(PROJECT_PATH)/run
SRC_DIR      = $(PROJECT_PATH)/src
TB_DIR       = $(PROJECT_PATH)/tb

# include modelsim flow makefile
include $(SCRIPTS_DIR)/modelsim_flow.mk
